//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrmBigDataFreqStatisticsServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:XrmBigDataFreqStatistics", ConfigurationName="XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType")]
    public interface XrmBigDataFreqStatisticsPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsAddRegulatory" +
            "DomainRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsAddRegulatory" +
            "DomainResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainResponse> RscSmsAddRegulatoryDomainAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsMonitorStatis" +
            "ticsRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsMonitorStatis" +
            "ticsResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsResponse> RscSmsMonitorStatisticsAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsAllResourceSt" +
            "atisticsRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsAllResourceSt" +
            "atisticsResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsResponse> RscSmsAllResourceStatisticsAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsAddRegulatory" +
            "ResourceRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsAddRegulatory" +
            "ResourceResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceResponse> RscSmsAddRegulatoryResourceAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsStationDetail" +
            "InfoRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsStationDetail" +
            "InfoResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoResponse> RscSmsStationDetailInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsQueryRegulato" +
            "ryDomainRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsQueryRegulato" +
            "ryDomainResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainResponse> RscSmsQueryRegulatoryDomainAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsMonitorTaskIn" +
            "foRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsMonitorTaskIn" +
            "foResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoResponse> RscSmsMonitorTaskInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsQueryStationI" +
            "nfoRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsQueryStationI" +
            "nfoResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoResponse> RscSmsQueryStationInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsQueryMStation" +
            "InfoRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsQueryMStation" +
            "InfoResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoResponse> RscSmsQueryMStationInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsQueryMStation" +
            "DetailInfoRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsQueryMStation" +
            "DetailInfoResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoResponse> RscSmsQueryMStationDetailInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsLayerMonitorS" +
            "tatisticsRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsLayerMonitorS" +
            "tatisticsResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsResponse> RscSmsLayerMonitorStatisticsAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsLayerMonitorD" +
            "etailInfoRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsLayerMonitorD" +
            "etailInfoResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoResponse> RscSmsLayerMonitorDetailInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsDelRegulatory" +
            "DomainRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsDelRegulatory" +
            "DomainResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainResponse> RscSmsDelRegulatoryDomainAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsDTMonitorDeta" +
            "ilInfoRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsDTMonitorDeta" +
            "ilInfoResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoResponse> RscSmsDTMonitorDetailInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsStationStatis" +
            "ticsInfoRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsStationStatis" +
            "ticsInfoResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoResponse> RscSmsStationStatisticsInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsDelRegulatory" +
            "ResourceRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsDelRegulatory" +
            "ResourceResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceResponse> RscSmsDelRegulatoryResourceAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsStationResour" +
            "ceStatisticsRequest", ReplyAction="urn:XrmBigDataFreqStatistics:XrmBigDataFreqStatisticsPortType:RscSmsStationResour" +
            "ceStatisticsResponse")]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsResponse> RscSmsStationResourceStatisticsAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsAddRegulatoryDomainRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsAddRegulatoryDomain", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainRequestBody Body;
        
        public RscSmsAddRegulatoryDomainRequest()
        {
        }
        
        public RscSmsAddRegulatoryDomainRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsAddRegulatoryDomainRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsAddRegulatoryDomainRequestBody()
        {
        }
        
        public RscSmsAddRegulatoryDomainRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsAddRegulatoryDomainResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsAddRegulatoryDomainResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainResponseBody Body;
        
        public RscSmsAddRegulatoryDomainResponse()
        {
        }
        
        public RscSmsAddRegulatoryDomainResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsAddRegulatoryDomainResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsAddRegulatoryDomainResponseBody()
        {
        }
        
        public RscSmsAddRegulatoryDomainResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsMonitorStatisticsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsMonitorStatistics", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsRequestBody Body;
        
        public RscSmsMonitorStatisticsRequest()
        {
        }
        
        public RscSmsMonitorStatisticsRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsMonitorStatisticsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsMonitorStatisticsRequestBody()
        {
        }
        
        public RscSmsMonitorStatisticsRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsMonitorStatisticsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsMonitorStatisticsResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsResponseBody Body;
        
        public RscSmsMonitorStatisticsResponse()
        {
        }
        
        public RscSmsMonitorStatisticsResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsMonitorStatisticsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsMonitorStatisticsResponseBody()
        {
        }
        
        public RscSmsMonitorStatisticsResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsAllResourceStatisticsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsAllResourceStatistics", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsRequestBody Body;
        
        public RscSmsAllResourceStatisticsRequest()
        {
        }
        
        public RscSmsAllResourceStatisticsRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsAllResourceStatisticsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsAllResourceStatisticsRequestBody()
        {
        }
        
        public RscSmsAllResourceStatisticsRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsAllResourceStatisticsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsAllResourceStatisticsResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsResponseBody Body;
        
        public RscSmsAllResourceStatisticsResponse()
        {
        }
        
        public RscSmsAllResourceStatisticsResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsAllResourceStatisticsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsAllResourceStatisticsResponseBody()
        {
        }
        
        public RscSmsAllResourceStatisticsResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsAddRegulatoryResourceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsAddRegulatoryResource", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceRequestBody Body;
        
        public RscSmsAddRegulatoryResourceRequest()
        {
        }
        
        public RscSmsAddRegulatoryResourceRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsAddRegulatoryResourceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsAddRegulatoryResourceRequestBody()
        {
        }
        
        public RscSmsAddRegulatoryResourceRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsAddRegulatoryResourceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsAddRegulatoryResourceResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceResponseBody Body;
        
        public RscSmsAddRegulatoryResourceResponse()
        {
        }
        
        public RscSmsAddRegulatoryResourceResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsAddRegulatoryResourceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsAddRegulatoryResourceResponseBody()
        {
        }
        
        public RscSmsAddRegulatoryResourceResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsStationDetailInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsStationDetailInfo", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoRequestBody Body;
        
        public RscSmsStationDetailInfoRequest()
        {
        }
        
        public RscSmsStationDetailInfoRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsStationDetailInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsStationDetailInfoRequestBody()
        {
        }
        
        public RscSmsStationDetailInfoRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsStationDetailInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsStationDetailInfoResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoResponseBody Body;
        
        public RscSmsStationDetailInfoResponse()
        {
        }
        
        public RscSmsStationDetailInfoResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsStationDetailInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsStationDetailInfoResponseBody()
        {
        }
        
        public RscSmsStationDetailInfoResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsQueryRegulatoryDomainRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsQueryRegulatoryDomain", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainRequestBody Body;
        
        public RscSmsQueryRegulatoryDomainRequest()
        {
        }
        
        public RscSmsQueryRegulatoryDomainRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsQueryRegulatoryDomainRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsQueryRegulatoryDomainRequestBody()
        {
        }
        
        public RscSmsQueryRegulatoryDomainRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsQueryRegulatoryDomainResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsQueryRegulatoryDomainResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainResponseBody Body;
        
        public RscSmsQueryRegulatoryDomainResponse()
        {
        }
        
        public RscSmsQueryRegulatoryDomainResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsQueryRegulatoryDomainResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsQueryRegulatoryDomainResponseBody()
        {
        }
        
        public RscSmsQueryRegulatoryDomainResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsMonitorTaskInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsMonitorTaskInfo", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoRequestBody Body;
        
        public RscSmsMonitorTaskInfoRequest()
        {
        }
        
        public RscSmsMonitorTaskInfoRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsMonitorTaskInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsMonitorTaskInfoRequestBody()
        {
        }
        
        public RscSmsMonitorTaskInfoRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsMonitorTaskInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsMonitorTaskInfoResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoResponseBody Body;
        
        public RscSmsMonitorTaskInfoResponse()
        {
        }
        
        public RscSmsMonitorTaskInfoResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsMonitorTaskInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsMonitorTaskInfoResponseBody()
        {
        }
        
        public RscSmsMonitorTaskInfoResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsQueryStationInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsQueryStationInfo", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoRequestBody Body;
        
        public RscSmsQueryStationInfoRequest()
        {
        }
        
        public RscSmsQueryStationInfoRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsQueryStationInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsQueryStationInfoRequestBody()
        {
        }
        
        public RscSmsQueryStationInfoRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsQueryStationInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsQueryStationInfoResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoResponseBody Body;
        
        public RscSmsQueryStationInfoResponse()
        {
        }
        
        public RscSmsQueryStationInfoResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsQueryStationInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsQueryStationInfoResponseBody()
        {
        }
        
        public RscSmsQueryStationInfoResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsQueryMStationInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsQueryMStationInfo", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoRequestBody Body;
        
        public RscSmsQueryMStationInfoRequest()
        {
        }
        
        public RscSmsQueryMStationInfoRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsQueryMStationInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsQueryMStationInfoRequestBody()
        {
        }
        
        public RscSmsQueryMStationInfoRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsQueryMStationInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsQueryMStationInfoResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoResponseBody Body;
        
        public RscSmsQueryMStationInfoResponse()
        {
        }
        
        public RscSmsQueryMStationInfoResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsQueryMStationInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsQueryMStationInfoResponseBody()
        {
        }
        
        public RscSmsQueryMStationInfoResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsQueryMStationDetailInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsQueryMStationDetailInfo", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoRequestBody Body;
        
        public RscSmsQueryMStationDetailInfoRequest()
        {
        }
        
        public RscSmsQueryMStationDetailInfoRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsQueryMStationDetailInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsQueryMStationDetailInfoRequestBody()
        {
        }
        
        public RscSmsQueryMStationDetailInfoRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsQueryMStationDetailInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsQueryMStationDetailInfoResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoResponseBody Body;
        
        public RscSmsQueryMStationDetailInfoResponse()
        {
        }
        
        public RscSmsQueryMStationDetailInfoResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsQueryMStationDetailInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsQueryMStationDetailInfoResponseBody()
        {
        }
        
        public RscSmsQueryMStationDetailInfoResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsLayerMonitorStatisticsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsLayerMonitorStatistics", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsRequestBody Body;
        
        public RscSmsLayerMonitorStatisticsRequest()
        {
        }
        
        public RscSmsLayerMonitorStatisticsRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsLayerMonitorStatisticsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsLayerMonitorStatisticsRequestBody()
        {
        }
        
        public RscSmsLayerMonitorStatisticsRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsLayerMonitorStatisticsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsLayerMonitorStatisticsResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsResponseBody Body;
        
        public RscSmsLayerMonitorStatisticsResponse()
        {
        }
        
        public RscSmsLayerMonitorStatisticsResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsLayerMonitorStatisticsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsLayerMonitorStatisticsResponseBody()
        {
        }
        
        public RscSmsLayerMonitorStatisticsResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsLayerMonitorDetailInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsLayerMonitorDetailInfo", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoRequestBody Body;
        
        public RscSmsLayerMonitorDetailInfoRequest()
        {
        }
        
        public RscSmsLayerMonitorDetailInfoRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsLayerMonitorDetailInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsLayerMonitorDetailInfoRequestBody()
        {
        }
        
        public RscSmsLayerMonitorDetailInfoRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsLayerMonitorDetailInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsLayerMonitorDetailInfoResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoResponseBody Body;
        
        public RscSmsLayerMonitorDetailInfoResponse()
        {
        }
        
        public RscSmsLayerMonitorDetailInfoResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsLayerMonitorDetailInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsLayerMonitorDetailInfoResponseBody()
        {
        }
        
        public RscSmsLayerMonitorDetailInfoResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsDelRegulatoryDomainRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsDelRegulatoryDomain", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainRequestBody Body;
        
        public RscSmsDelRegulatoryDomainRequest()
        {
        }
        
        public RscSmsDelRegulatoryDomainRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsDelRegulatoryDomainRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsDelRegulatoryDomainRequestBody()
        {
        }
        
        public RscSmsDelRegulatoryDomainRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsDelRegulatoryDomainResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsDelRegulatoryDomainResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainResponseBody Body;
        
        public RscSmsDelRegulatoryDomainResponse()
        {
        }
        
        public RscSmsDelRegulatoryDomainResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsDelRegulatoryDomainResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsDelRegulatoryDomainResponseBody()
        {
        }
        
        public RscSmsDelRegulatoryDomainResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsDTMonitorDetailInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsDTMonitorDetailInfo", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoRequestBody Body;
        
        public RscSmsDTMonitorDetailInfoRequest()
        {
        }
        
        public RscSmsDTMonitorDetailInfoRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsDTMonitorDetailInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsDTMonitorDetailInfoRequestBody()
        {
        }
        
        public RscSmsDTMonitorDetailInfoRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsDTMonitorDetailInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsDTMonitorDetailInfoResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoResponseBody Body;
        
        public RscSmsDTMonitorDetailInfoResponse()
        {
        }
        
        public RscSmsDTMonitorDetailInfoResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsDTMonitorDetailInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsDTMonitorDetailInfoResponseBody()
        {
        }
        
        public RscSmsDTMonitorDetailInfoResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsStationStatisticsInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsStationStatisticsInfo", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoRequestBody Body;
        
        public RscSmsStationStatisticsInfoRequest()
        {
        }
        
        public RscSmsStationStatisticsInfoRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsStationStatisticsInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsStationStatisticsInfoRequestBody()
        {
        }
        
        public RscSmsStationStatisticsInfoRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsStationStatisticsInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsStationStatisticsInfoResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoResponseBody Body;
        
        public RscSmsStationStatisticsInfoResponse()
        {
        }
        
        public RscSmsStationStatisticsInfoResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsStationStatisticsInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsStationStatisticsInfoResponseBody()
        {
        }
        
        public RscSmsStationStatisticsInfoResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsDelRegulatoryResourceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsDelRegulatoryResource", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceRequestBody Body;
        
        public RscSmsDelRegulatoryResourceRequest()
        {
        }
        
        public RscSmsDelRegulatoryResourceRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsDelRegulatoryResourceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsDelRegulatoryResourceRequestBody()
        {
        }
        
        public RscSmsDelRegulatoryResourceRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsDelRegulatoryResourceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsDelRegulatoryResourceResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceResponseBody Body;
        
        public RscSmsDelRegulatoryResourceResponse()
        {
        }
        
        public RscSmsDelRegulatoryResourceResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsDelRegulatoryResourceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsDelRegulatoryResourceResponseBody()
        {
        }
        
        public RscSmsDelRegulatoryResourceResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsStationResourceStatisticsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsStationResourceStatistics", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsRequestBody Body;
        
        public RscSmsStationResourceStatisticsRequest()
        {
        }
        
        public RscSmsStationResourceStatisticsRequest(XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsStationResourceStatisticsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sInput;
        
        public RscSmsStationResourceStatisticsRequestBody()
        {
        }
        
        public RscSmsStationResourceStatisticsRequestBody(string sInput)
        {
            this.sInput = sInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RscSmsStationResourceStatisticsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RscSmsStationResourceStatisticsResponse", Namespace="urn:XrmBigDataFreqStatistics", Order=0)]
        public XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsResponseBody Body;
        
        public RscSmsStationResourceStatisticsResponse()
        {
        }
        
        public RscSmsStationResourceStatisticsResponse(XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RscSmsStationResourceStatisticsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sOutput;
        
        public RscSmsStationResourceStatisticsResponseBody()
        {
        }
        
        public RscSmsStationResourceStatisticsResponseBody(string sOutput)
        {
            this.sOutput = sOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface XrmBigDataFreqStatisticsPortTypeChannel : XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class XrmBigDataFreqStatisticsPortTypeClient : System.ServiceModel.ClientBase<XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType>, XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public XrmBigDataFreqStatisticsPortTypeClient() : 
                base(XrmBigDataFreqStatisticsPortTypeClient.GetDefaultBinding(), XrmBigDataFreqStatisticsPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.XrmBigDataFreqStatistics.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XrmBigDataFreqStatisticsPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(XrmBigDataFreqStatisticsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), XrmBigDataFreqStatisticsPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XrmBigDataFreqStatisticsPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(XrmBigDataFreqStatisticsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XrmBigDataFreqStatisticsPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(XrmBigDataFreqStatisticsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XrmBigDataFreqStatisticsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsAddRegulatoryDomainAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainRequest request)
        {
            return base.Channel.RscSmsAddRegulatoryDomainAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainResponse> RscSmsAddRegulatoryDomainAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryDomainRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsAddRegulatoryDomainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsMonitorStatisticsAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsRequest request)
        {
            return base.Channel.RscSmsMonitorStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsResponse> RscSmsMonitorStatisticsAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorStatisticsRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsMonitorStatisticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsAllResourceStatisticsAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsRequest request)
        {
            return base.Channel.RscSmsAllResourceStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsResponse> RscSmsAllResourceStatisticsAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsAllResourceStatisticsRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsAllResourceStatisticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsAddRegulatoryResourceAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceRequest request)
        {
            return base.Channel.RscSmsAddRegulatoryResourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceResponse> RscSmsAddRegulatoryResourceAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsAddRegulatoryResourceRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsAddRegulatoryResourceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsStationDetailInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoRequest request)
        {
            return base.Channel.RscSmsStationDetailInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoResponse> RscSmsStationDetailInfoAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsStationDetailInfoRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsStationDetailInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsQueryRegulatoryDomainAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainRequest request)
        {
            return base.Channel.RscSmsQueryRegulatoryDomainAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainResponse> RscSmsQueryRegulatoryDomainAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsQueryRegulatoryDomainRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsQueryRegulatoryDomainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsMonitorTaskInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoRequest request)
        {
            return base.Channel.RscSmsMonitorTaskInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoResponse> RscSmsMonitorTaskInfoAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsMonitorTaskInfoRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsMonitorTaskInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsQueryStationInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoRequest request)
        {
            return base.Channel.RscSmsQueryStationInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoResponse> RscSmsQueryStationInfoAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsQueryStationInfoRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsQueryStationInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsQueryMStationInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoRequest request)
        {
            return base.Channel.RscSmsQueryMStationInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoResponse> RscSmsQueryMStationInfoAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationInfoRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsQueryMStationInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsQueryMStationDetailInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoRequest request)
        {
            return base.Channel.RscSmsQueryMStationDetailInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoResponse> RscSmsQueryMStationDetailInfoAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsQueryMStationDetailInfoRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsQueryMStationDetailInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsLayerMonitorStatisticsAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsRequest request)
        {
            return base.Channel.RscSmsLayerMonitorStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsResponse> RscSmsLayerMonitorStatisticsAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorStatisticsRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsLayerMonitorStatisticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsLayerMonitorDetailInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoRequest request)
        {
            return base.Channel.RscSmsLayerMonitorDetailInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoResponse> RscSmsLayerMonitorDetailInfoAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsLayerMonitorDetailInfoRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsLayerMonitorDetailInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsDelRegulatoryDomainAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainRequest request)
        {
            return base.Channel.RscSmsDelRegulatoryDomainAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainResponse> RscSmsDelRegulatoryDomainAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryDomainRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsDelRegulatoryDomainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsDTMonitorDetailInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoRequest request)
        {
            return base.Channel.RscSmsDTMonitorDetailInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoResponse> RscSmsDTMonitorDetailInfoAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsDTMonitorDetailInfoRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsDTMonitorDetailInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsStationStatisticsInfoAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoRequest request)
        {
            return base.Channel.RscSmsStationStatisticsInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoResponse> RscSmsStationStatisticsInfoAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsStationStatisticsInfoRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsStationStatisticsInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsDelRegulatoryResourceAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceRequest request)
        {
            return base.Channel.RscSmsDelRegulatoryResourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceResponse> RscSmsDelRegulatoryResourceAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsDelRegulatoryResourceRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsDelRegulatoryResourceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsResponse> XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType.RscSmsStationResourceStatisticsAsync(XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsRequest request)
        {
            return base.Channel.RscSmsStationResourceStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsResponse> RscSmsStationResourceStatisticsAsync(string sInput)
        {
            XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsRequest inValue = new XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsRequest();
            inValue.Body = new XrmBigDataFreqStatisticsServiceReference.RscSmsStationResourceStatisticsRequestBody();
            inValue.Body.sInput = sInput;
            return ((XrmBigDataFreqStatisticsServiceReference.XrmBigDataFreqStatisticsPortType)(this)).RscSmsStationResourceStatisticsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XrmBigDataFreqStatistics))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XrmBigDataFreqStatistics))
            {
                //return new System.ServiceModel.EndpointAddress("http://202.101.191.36:7055/services/XrmBigDataFreqStatistics.XrmBigDataFreqStatis" +  "tics/");
                return new System.ServiceModel.EndpointAddress("http://202.101.191.36:7055/rmas/services/XrmBigDataFreqStatistics?wsdl");
                
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return XrmBigDataFreqStatisticsPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.XrmBigDataFreqStatistics);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return XrmBigDataFreqStatisticsPortTypeClient.GetEndpointAddress(EndpointConfiguration.XrmBigDataFreqStatistics);
        }
        
        public enum EndpointConfiguration
        {
            
            XrmBigDataFreqStatistics,
        }
    }
}
