//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://standard.monitor.rmas.com", ConfigurationName="StandardService.StandardServiceSoap")]
    public interface StandardServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="S_SglFreqMeasure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_SglFreqMeasureResponse> S_SglFreqMeasureAsync(StandardService.S_SglFreqMeasureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_TaskModification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_TaskModificationResponse> S_TaskModificationAsync(StandardService.S_TaskModificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_WBFFTMon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_WBFFTMonResponse> S_WBFFTMonAsync(StandardService.S_WBFFTMonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_FScan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_FScanResponse> S_FScanAsync(StandardService.S_FScanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_MScan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_MScanResponse> S_MScanAsync(StandardService.S_MScanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_IFDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_IFDFResponse> S_IFDFAsync(StandardService.S_IFDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_SglFreqDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_SglFreqDFResponse> S_SglFreqDFAsync(StandardService.S_SglFreqDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_WBDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_WBDFResponse> S_WBDFAsync(StandardService.S_WBDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_FScanDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_FScanDFResponse> S_FScanDFAsync(StandardService.S_FScanDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_MScanDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_MScanDFResponse> S_MScanDFAsync(StandardService.S_MScanDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_OccupancyMeas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_OccupancyMeasResponse> S_OccupancyMeasAsync(StandardService.S_OccupancyMeasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_GenIFSpectrumTemplate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_GenIFSpectrumTemplateResponse> S_GenIFSpectrumTemplateAsync(StandardService.S_GenIFSpectrumTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_GenWBSpectrumTemplate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_GenWBSpectrumTemplateResponse> S_GenWBSpectrumTemplateAsync(StandardService.S_GenWBSpectrumTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_GenFScanSpectrumTemplate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_GenFScanSpectrumTemplateResponse> S_GenFScanSpectrumTemplateAsync(StandardService.S_GenFScanSpectrumTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_IFSignalIntercept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_IFSignalInterceptResponse> S_IFSignalInterceptAsync(StandardService.S_IFSignalInterceptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_WBSignalIntercept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_WBSignalInterceptResponse> S_WBSignalInterceptAsync(StandardService.S_WBSignalInterceptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_FScanSignalIntercept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_FScanSignalInterceptResponse> S_FScanSignalInterceptAsync(StandardService.S_FScanSignalInterceptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_DigitalSignalRecDecode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_DigitalSignalRecDecodeResponse> S_DigitalSignalRecDecodeAsync(StandardService.S_DigitalSignalRecDecodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_AnalogTVDemod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_AnalogTVDemodResponse> S_AnalogTVDemodAsync(StandardService.S_AnalogTVDemodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_DigitalTVDem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_DigitalTVDemResponse> S_DigitalTVDemAsync(StandardService.S_DigitalTVDemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_DigitalBroadcastDem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_DigitalBroadcastDemResponse> S_DigitalBroadcastDemAsync(StandardService.S_DigitalBroadcastDemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_SpecCommSysSignalDem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_SpecCommSysSignalDemResponse> S_SpecCommSysSignalDemAsync(StandardService.S_SpecCommSysSignalDemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_StopMeasure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_StopMeasureResponse> S_StopMeasureAsync(StandardService.S_StopMeasureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_SelfTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_SelfTestResponse> S_SelfTestAsync(StandardService.S_SelfTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_QueryFacilityDevStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_QueryFacilityDevStatusResponse> S_QueryFacilityDevStatusAsync(StandardService.S_QueryFacilityDevStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_SetDevicePower", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_SetDevicePowerResponse> S_SetDevicePowerAsync(StandardService.S_SetDevicePowerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="S_LinkAntennaDev", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StandardService.S_LinkAntennaDevResponse> S_LinkAntennaDevAsync(StandardService.S_LinkAntennaDevRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_SglFreqMeasureRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ssglfreqmeasure.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_SglFreqMeasureRequest()
        {
        }
        
        public S_SglFreqMeasureRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_SglFreqMeasureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ssglfreqmeasure.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_SglFreqMeasureResponse()
        {
        }
        
        public S_SglFreqMeasureResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_TaskModificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://staskmodification.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_TaskModificationRequest()
        {
        }
        
        public S_TaskModificationRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_TaskModificationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://staskmodification.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_TaskModificationResponse()
        {
        }
        
        public S_TaskModificationResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_WBFFTMonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swbfftmon.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_WBFFTMonRequest()
        {
        }
        
        public S_WBFFTMonRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_WBFFTMonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swbfftmon.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_WBFFTMonResponse()
        {
        }
        
        public S_WBFFTMonResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_FScanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sfscan.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_FScanRequest()
        {
        }
        
        public S_FScanRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_FScanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sfscan.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_FScanResponse()
        {
        }
        
        public S_FScanResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_MScanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smscan.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_MScanRequest()
        {
        }
        
        public S_MScanRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_MScanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smscan.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_MScanResponse()
        {
        }
        
        public S_MScanResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_IFDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sifdf.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_IFDFRequest()
        {
        }
        
        public S_IFDFRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_IFDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sifdf.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_IFDFResponse()
        {
        }
        
        public S_IFDFResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_SglFreqDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ssglfreqdf.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_SglFreqDFRequest()
        {
        }
        
        public S_SglFreqDFRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_SglFreqDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ssglfreqdf.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_SglFreqDFResponse()
        {
        }
        
        public S_SglFreqDFResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_WBDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swbdf.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_WBDFRequest()
        {
        }
        
        public S_WBDFRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_WBDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swbdf.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_WBDFResponse()
        {
        }
        
        public S_WBDFResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_FScanDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sfscandf.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_FScanDFRequest()
        {
        }
        
        public S_FScanDFRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_FScanDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sfscandf.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_FScanDFResponse()
        {
        }
        
        public S_FScanDFResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_MScanDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smscandf.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_MScanDFRequest()
        {
        }
        
        public S_MScanDFRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_MScanDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smscandf.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_MScanDFResponse()
        {
        }
        
        public S_MScanDFResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_OccupancyMeasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soccupancymeas.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_OccupancyMeasRequest()
        {
        }
        
        public S_OccupancyMeasRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_OccupancyMeasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soccupancymeas.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_OccupancyMeasResponse()
        {
        }
        
        public S_OccupancyMeasResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_GenIFSpectrumTemplateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sgenifspectrumtemplate.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_GenIFSpectrumTemplateRequest()
        {
        }
        
        public S_GenIFSpectrumTemplateRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_GenIFSpectrumTemplateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sgenifspectrumtemplate.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_GenIFSpectrumTemplateResponse()
        {
        }
        
        public S_GenIFSpectrumTemplateResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_GenWBSpectrumTemplateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sgenwbspectrumtemplate.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_GenWBSpectrumTemplateRequest()
        {
        }
        
        public S_GenWBSpectrumTemplateRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_GenWBSpectrumTemplateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sgenwbspectrumtemplate.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_GenWBSpectrumTemplateResponse()
        {
        }
        
        public S_GenWBSpectrumTemplateResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_GenFScanSpectrumTemplateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sgenfscanspectrumtemplate.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_GenFScanSpectrumTemplateRequest()
        {
        }
        
        public S_GenFScanSpectrumTemplateRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_GenFScanSpectrumTemplateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sgenfscanspectrumtemplate.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_GenFScanSpectrumTemplateResponse()
        {
        }
        
        public S_GenFScanSpectrumTemplateResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_IFSignalInterceptRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sifsignalintercept.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_IFSignalInterceptRequest()
        {
        }
        
        public S_IFSignalInterceptRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_IFSignalInterceptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sifsignalintercept.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_IFSignalInterceptResponse()
        {
        }
        
        public S_IFSignalInterceptResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_WBSignalInterceptRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swbsignalintercept.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_WBSignalInterceptRequest()
        {
        }
        
        public S_WBSignalInterceptRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_WBSignalInterceptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://swbsignalintercept.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_WBSignalInterceptResponse()
        {
        }
        
        public S_WBSignalInterceptResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_FScanSignalInterceptRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sfscansignalintercept.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_FScanSignalInterceptRequest()
        {
        }
        
        public S_FScanSignalInterceptRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_FScanSignalInterceptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sfscansignalintercept.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_FScanSignalInterceptResponse()
        {
        }
        
        public S_FScanSignalInterceptResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_DigitalSignalRecDecodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdigitalsignalrecdecode.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_DigitalSignalRecDecodeRequest()
        {
        }
        
        public S_DigitalSignalRecDecodeRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_DigitalSignalRecDecodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdigitalsignalrecdecode.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_DigitalSignalRecDecodeResponse()
        {
        }
        
        public S_DigitalSignalRecDecodeResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_AnalogTVDemodRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sanalogtvdemod.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_AnalogTVDemodRequest()
        {
        }
        
        public S_AnalogTVDemodRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_AnalogTVDemodResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sanalogtvdemod.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_AnalogTVDemodResponse()
        {
        }
        
        public S_AnalogTVDemodResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_DigitalTVDemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdigitaltvdem.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_DigitalTVDemRequest()
        {
        }
        
        public S_DigitalTVDemRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_DigitalTVDemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdigitaltvdem.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_DigitalTVDemResponse()
        {
        }
        
        public S_DigitalTVDemResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_DigitalBroadcastDemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdigitalbroadcastdem.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_DigitalBroadcastDemRequest()
        {
        }
        
        public S_DigitalBroadcastDemRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_DigitalBroadcastDemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdigitalbroadcastdem.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_DigitalBroadcastDemResponse()
        {
        }
        
        public S_DigitalBroadcastDemResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_SpecCommSysSignalDemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sspeccommsyssignaldem.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_SpecCommSysSignalDemRequest()
        {
        }
        
        public S_SpecCommSysSignalDemRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_SpecCommSysSignalDemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sspeccommsyssignaldem.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_SpecCommSysSignalDemResponse()
        {
        }
        
        public S_SpecCommSysSignalDemResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_StopMeasureRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sstopmeasure.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_StopMeasureRequest()
        {
        }
        
        public S_StopMeasureRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_StopMeasureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sstopmeasure.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_StopMeasureResponse()
        {
        }
        
        public S_StopMeasureResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_SelfTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sselftest.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_SelfTestRequest()
        {
        }
        
        public S_SelfTestRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_SelfTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sselftest.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_SelfTestResponse()
        {
        }
        
        public S_SelfTestResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_QueryFacilityDevStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://squeryfacilitydevstatus.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_QueryFacilityDevStatusRequest()
        {
        }
        
        public S_QueryFacilityDevStatusRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_QueryFacilityDevStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://squeryfacilitydevstatus.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_QueryFacilityDevStatusResponse()
        {
        }
        
        public S_QueryFacilityDevStatusResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_SetDevicePowerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ssetdevicepower.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_SetDevicePowerRequest()
        {
        }
        
        public S_SetDevicePowerRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_SetDevicePowerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ssetdevicepower.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_SetDevicePowerResponse()
        {
        }
        
        public S_SetDevicePowerResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_LinkAntennaDevRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://slinkantennadev.standard.monitor.rmas.com/xsd", Order=0)]
        public string input;
        
        public S_LinkAntennaDevRequest()
        {
        }
        
        public S_LinkAntennaDevRequest(string input)
        {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class S_LinkAntennaDevResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://slinkantennadev.standard.monitor.rmas.com/xsd", Order=0)]
        public string output;
        
        public S_LinkAntennaDevResponse()
        {
        }
        
        public S_LinkAntennaDevResponse(string output)
        {
            this.output = output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface StandardServiceSoapChannel : StandardService.StandardServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class StandardServiceSoapClient : System.ServiceModel.ClientBase<StandardService.StandardServiceSoap>, StandardService.StandardServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public StandardServiceSoapClient() : 
                base(StandardServiceSoapClient.GetDefaultBinding(), StandardServiceSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.StandardServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StandardServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(StandardServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), StandardServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StandardServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StandardServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StandardServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StandardServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StandardServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_SglFreqMeasureResponse> StandardService.StandardServiceSoap.S_SglFreqMeasureAsync(StandardService.S_SglFreqMeasureRequest request)
        {
            return base.Channel.S_SglFreqMeasureAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_SglFreqMeasureResponse> S_SglFreqMeasureAsync(string input)
        {
            StandardService.S_SglFreqMeasureRequest inValue = new StandardService.S_SglFreqMeasureRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_SglFreqMeasureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_TaskModificationResponse> StandardService.StandardServiceSoap.S_TaskModificationAsync(StandardService.S_TaskModificationRequest request)
        {
            return base.Channel.S_TaskModificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_TaskModificationResponse> S_TaskModificationAsync(string input)
        {
            StandardService.S_TaskModificationRequest inValue = new StandardService.S_TaskModificationRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_TaskModificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_WBFFTMonResponse> StandardService.StandardServiceSoap.S_WBFFTMonAsync(StandardService.S_WBFFTMonRequest request)
        {
            return base.Channel.S_WBFFTMonAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_WBFFTMonResponse> S_WBFFTMonAsync(string input)
        {
            StandardService.S_WBFFTMonRequest inValue = new StandardService.S_WBFFTMonRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_WBFFTMonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_FScanResponse> StandardService.StandardServiceSoap.S_FScanAsync(StandardService.S_FScanRequest request)
        {
            return base.Channel.S_FScanAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_FScanResponse> S_FScanAsync(string input)
        {
            StandardService.S_FScanRequest inValue = new StandardService.S_FScanRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_FScanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_MScanResponse> StandardService.StandardServiceSoap.S_MScanAsync(StandardService.S_MScanRequest request)
        {
            return base.Channel.S_MScanAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_MScanResponse> S_MScanAsync(string input)
        {
            StandardService.S_MScanRequest inValue = new StandardService.S_MScanRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_MScanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_IFDFResponse> StandardService.StandardServiceSoap.S_IFDFAsync(StandardService.S_IFDFRequest request)
        {
            return base.Channel.S_IFDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_IFDFResponse> S_IFDFAsync(string input)
        {
            StandardService.S_IFDFRequest inValue = new StandardService.S_IFDFRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_IFDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_SglFreqDFResponse> StandardService.StandardServiceSoap.S_SglFreqDFAsync(StandardService.S_SglFreqDFRequest request)
        {
            return base.Channel.S_SglFreqDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_SglFreqDFResponse> S_SglFreqDFAsync(string input)
        {
            StandardService.S_SglFreqDFRequest inValue = new StandardService.S_SglFreqDFRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_SglFreqDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_WBDFResponse> StandardService.StandardServiceSoap.S_WBDFAsync(StandardService.S_WBDFRequest request)
        {
            return base.Channel.S_WBDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_WBDFResponse> S_WBDFAsync(string input)
        {
            StandardService.S_WBDFRequest inValue = new StandardService.S_WBDFRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_WBDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_FScanDFResponse> StandardService.StandardServiceSoap.S_FScanDFAsync(StandardService.S_FScanDFRequest request)
        {
            return base.Channel.S_FScanDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_FScanDFResponse> S_FScanDFAsync(string input)
        {
            StandardService.S_FScanDFRequest inValue = new StandardService.S_FScanDFRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_FScanDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_MScanDFResponse> StandardService.StandardServiceSoap.S_MScanDFAsync(StandardService.S_MScanDFRequest request)
        {
            return base.Channel.S_MScanDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_MScanDFResponse> S_MScanDFAsync(string input)
        {
            StandardService.S_MScanDFRequest inValue = new StandardService.S_MScanDFRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_MScanDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_OccupancyMeasResponse> StandardService.StandardServiceSoap.S_OccupancyMeasAsync(StandardService.S_OccupancyMeasRequest request)
        {
            return base.Channel.S_OccupancyMeasAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_OccupancyMeasResponse> S_OccupancyMeasAsync(string input)
        {
            StandardService.S_OccupancyMeasRequest inValue = new StandardService.S_OccupancyMeasRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_OccupancyMeasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_GenIFSpectrumTemplateResponse> StandardService.StandardServiceSoap.S_GenIFSpectrumTemplateAsync(StandardService.S_GenIFSpectrumTemplateRequest request)
        {
            return base.Channel.S_GenIFSpectrumTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_GenIFSpectrumTemplateResponse> S_GenIFSpectrumTemplateAsync(string input)
        {
            StandardService.S_GenIFSpectrumTemplateRequest inValue = new StandardService.S_GenIFSpectrumTemplateRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_GenIFSpectrumTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_GenWBSpectrumTemplateResponse> StandardService.StandardServiceSoap.S_GenWBSpectrumTemplateAsync(StandardService.S_GenWBSpectrumTemplateRequest request)
        {
            return base.Channel.S_GenWBSpectrumTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_GenWBSpectrumTemplateResponse> S_GenWBSpectrumTemplateAsync(string input)
        {
            StandardService.S_GenWBSpectrumTemplateRequest inValue = new StandardService.S_GenWBSpectrumTemplateRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_GenWBSpectrumTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_GenFScanSpectrumTemplateResponse> StandardService.StandardServiceSoap.S_GenFScanSpectrumTemplateAsync(StandardService.S_GenFScanSpectrumTemplateRequest request)
        {
            return base.Channel.S_GenFScanSpectrumTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_GenFScanSpectrumTemplateResponse> S_GenFScanSpectrumTemplateAsync(string input)
        {
            StandardService.S_GenFScanSpectrumTemplateRequest inValue = new StandardService.S_GenFScanSpectrumTemplateRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_GenFScanSpectrumTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_IFSignalInterceptResponse> StandardService.StandardServiceSoap.S_IFSignalInterceptAsync(StandardService.S_IFSignalInterceptRequest request)
        {
            return base.Channel.S_IFSignalInterceptAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_IFSignalInterceptResponse> S_IFSignalInterceptAsync(string input)
        {
            StandardService.S_IFSignalInterceptRequest inValue = new StandardService.S_IFSignalInterceptRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_IFSignalInterceptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_WBSignalInterceptResponse> StandardService.StandardServiceSoap.S_WBSignalInterceptAsync(StandardService.S_WBSignalInterceptRequest request)
        {
            return base.Channel.S_WBSignalInterceptAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_WBSignalInterceptResponse> S_WBSignalInterceptAsync(string input)
        {
            StandardService.S_WBSignalInterceptRequest inValue = new StandardService.S_WBSignalInterceptRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_WBSignalInterceptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_FScanSignalInterceptResponse> StandardService.StandardServiceSoap.S_FScanSignalInterceptAsync(StandardService.S_FScanSignalInterceptRequest request)
        {
            return base.Channel.S_FScanSignalInterceptAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_FScanSignalInterceptResponse> S_FScanSignalInterceptAsync(string input)
        {
            StandardService.S_FScanSignalInterceptRequest inValue = new StandardService.S_FScanSignalInterceptRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_FScanSignalInterceptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_DigitalSignalRecDecodeResponse> StandardService.StandardServiceSoap.S_DigitalSignalRecDecodeAsync(StandardService.S_DigitalSignalRecDecodeRequest request)
        {
            return base.Channel.S_DigitalSignalRecDecodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_DigitalSignalRecDecodeResponse> S_DigitalSignalRecDecodeAsync(string input)
        {
            StandardService.S_DigitalSignalRecDecodeRequest inValue = new StandardService.S_DigitalSignalRecDecodeRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_DigitalSignalRecDecodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_AnalogTVDemodResponse> StandardService.StandardServiceSoap.S_AnalogTVDemodAsync(StandardService.S_AnalogTVDemodRequest request)
        {
            return base.Channel.S_AnalogTVDemodAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_AnalogTVDemodResponse> S_AnalogTVDemodAsync(string input)
        {
            StandardService.S_AnalogTVDemodRequest inValue = new StandardService.S_AnalogTVDemodRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_AnalogTVDemodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_DigitalTVDemResponse> StandardService.StandardServiceSoap.S_DigitalTVDemAsync(StandardService.S_DigitalTVDemRequest request)
        {
            return base.Channel.S_DigitalTVDemAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_DigitalTVDemResponse> S_DigitalTVDemAsync(string input)
        {
            StandardService.S_DigitalTVDemRequest inValue = new StandardService.S_DigitalTVDemRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_DigitalTVDemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_DigitalBroadcastDemResponse> StandardService.StandardServiceSoap.S_DigitalBroadcastDemAsync(StandardService.S_DigitalBroadcastDemRequest request)
        {
            return base.Channel.S_DigitalBroadcastDemAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_DigitalBroadcastDemResponse> S_DigitalBroadcastDemAsync(string input)
        {
            StandardService.S_DigitalBroadcastDemRequest inValue = new StandardService.S_DigitalBroadcastDemRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_DigitalBroadcastDemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_SpecCommSysSignalDemResponse> StandardService.StandardServiceSoap.S_SpecCommSysSignalDemAsync(StandardService.S_SpecCommSysSignalDemRequest request)
        {
            return base.Channel.S_SpecCommSysSignalDemAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_SpecCommSysSignalDemResponse> S_SpecCommSysSignalDemAsync(string input)
        {
            StandardService.S_SpecCommSysSignalDemRequest inValue = new StandardService.S_SpecCommSysSignalDemRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_SpecCommSysSignalDemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_StopMeasureResponse> StandardService.StandardServiceSoap.S_StopMeasureAsync(StandardService.S_StopMeasureRequest request)
        {
            return base.Channel.S_StopMeasureAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_StopMeasureResponse> S_StopMeasureAsync(string input)
        {
            StandardService.S_StopMeasureRequest inValue = new StandardService.S_StopMeasureRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_StopMeasureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_SelfTestResponse> StandardService.StandardServiceSoap.S_SelfTestAsync(StandardService.S_SelfTestRequest request)
        {
            return base.Channel.S_SelfTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_SelfTestResponse> S_SelfTestAsync(string input)
        {
            StandardService.S_SelfTestRequest inValue = new StandardService.S_SelfTestRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_SelfTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_QueryFacilityDevStatusResponse> StandardService.StandardServiceSoap.S_QueryFacilityDevStatusAsync(StandardService.S_QueryFacilityDevStatusRequest request)
        {
            return base.Channel.S_QueryFacilityDevStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_QueryFacilityDevStatusResponse> S_QueryFacilityDevStatusAsync(string input)
        {
            StandardService.S_QueryFacilityDevStatusRequest inValue = new StandardService.S_QueryFacilityDevStatusRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_QueryFacilityDevStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_SetDevicePowerResponse> StandardService.StandardServiceSoap.S_SetDevicePowerAsync(StandardService.S_SetDevicePowerRequest request)
        {
            return base.Channel.S_SetDevicePowerAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_SetDevicePowerResponse> S_SetDevicePowerAsync(string input)
        {
            StandardService.S_SetDevicePowerRequest inValue = new StandardService.S_SetDevicePowerRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_SetDevicePowerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StandardService.S_LinkAntennaDevResponse> StandardService.StandardServiceSoap.S_LinkAntennaDevAsync(StandardService.S_LinkAntennaDevRequest request)
        {
            return base.Channel.S_LinkAntennaDevAsync(request);
        }
        
        public System.Threading.Tasks.Task<StandardService.S_LinkAntennaDevResponse> S_LinkAntennaDevAsync(string input)
        {
            StandardService.S_LinkAntennaDevRequest inValue = new StandardService.S_LinkAntennaDevRequest();
            inValue.input = input;
            return ((StandardService.StandardServiceSoap)(this)).S_LinkAntennaDevAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.StandardServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.StandardServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://202.101.191.36/services/StandardService/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return StandardServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.StandardServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return StandardServiceSoapClient.GetEndpointAddress(EndpointConfiguration.StandardServiceSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            StandardServiceSoap,
        }
    }
}
